version: '3.3'

services:
  ngapimock-standalone:
    image: ngapimock/standalone:latest
    restart: always
    ports:
      - '0.0.0.0:4000:3000'
    volumes:
      - ./mocks:/opt/ngapimock/mocks
      - ./extension.js:/opt/ngapimock/extension.js
      - ./configuration.json:/opt/ngapimock/configuration.json
